### ISSUE TITLE
삼거리(갈림길) 이름 작명

### ISSUE THREAD

**Issue by HoraceVelmont** [CienProject2014/OneLevelHero_ProposalTeam#10]
![worldmap_light](https://cloud.githubusercontent.com/assets/3744320/5675691/2869eeb2-9808-11e4-9cbf-87636088a9ab.png)

1~6번 갈림길(삼거리)에 대한 이름을 짓는다

**Comment by koreakid91** [comment]
1. 회군의 바위
2. 도그베네핏 야영지
3. 공동묘지
4. 여행자의 쉼터
5. 모에라에 신전 입구
6. 황금 풍뎅이 석상

**Comment by koreakid91** [comment]
갓대훈개트롤

**Comment by koreakid91** [comment]
1.Retreat stone
2.Dogbenefit camp
3.Cemetery
4.Caravanserial place
5.Entrance of Moerae shrine
6.Golden beetle stone statue

**Comment by HoraceVelmont** [comment]
감사합니다
