### ISSUE TITLE
배틀 로직 기획서 - 1차

### ISSUE THREAD

**Issue by HoraceVelmont** [CienProject2014/OneLevelHero_ProposalTeam#12]
배틀 로직과 관련된 기획서 첨부 요망

**Comment by Redrock912** [comment]
https://drive.google.com/drive/#folders/0B-0MK9Y1-n7JclFtUllublctSFU/0B-0MK9Y1-n7JS1ZJMWtTWnRVcW8 전투 시스템

**Comment by HoraceVelmont** [comment]
감사합니다

**Comment by HoraceVelmont** [comment]
없어졌어요!

**Comment by soyagok11** [comment]
수정중

**Comment by Redrock912** [comment]
다시 올렸어요~
https://drive.google.com/drive/#folders/0B-0MK9Y1-n7JclFtUllublctSFU/0B-0MK9Y1-n7JS1ZJMWtTWnRVcW8/0B-H0_4MOLcCZbzBVTmZoRWl0bmc
