### ISSUE TITLE
NPC선택 씬 / 채팅 대화씬 에서의 배치구조문제

### ISSUE THREAD

**Issue by HoraceVelmont** [CienProject2014/OneLevelHero_ProposalTeam#18]
NPC가 등장하여 이벤트를 선택하는 씬과
채팅 씬에서의 배치구조 확립

**Comment by soyagok11** [comment]
https://drive.google.com/file/d/0B-0MK9Y1-n7JYkRsal9rNjN6cE0/view?usp=sharing

**Comment by zingzing2323** [comment]
이거 해결됬나요?

**Comment by zingzing2323** [comment]
@soyagok11 아직 기획서가 수정이 안됬어요 ! ㅜㅜ
곧 수정해서 업로드 할 예정 (1/19)

**Comment by dbstn003** [comment]
1. 화면의 왼쪽에 용사일행 중 말하는 사람, 화면의 오른쪽에 NPC일행 중 말하는 사람의 이미지 표시
말하는 자는 이미지가 조금 커짐. 말하는 자가 바뀌면 다시 작아짐

2. 현재 대화하고 있는 모든 npc를 화면에 표시. 말하는 npc는 확대됨. 용사일행이 말할 때는 모두 원래 크기로 하고 용사일행 중 누가 말하는 지는 이름으로 분간하기. 또는 어딘가에 이미지 표시

우선 1번으로 되어 있으나 2번에서 용사일행 분간법 중 깔끔할게 있으면 2번으로 할 수도 있음

**Comment by dbstn003** [comment]
용사일행과 npc와의 대화에서 왼쪽엔 용사일행 중 말하는 사람, 오른쪽엔 npc 일행 중 말하는 사람
말하는 자는 이미지가 조금 커짐. 말하는 자가 바뀌면 다시 작아짐

용사일행 내부에서의 대화인 경우 왼쪽, 오른쪽에 제약을 두지 않음.
