### ISSUE TITLE
엔딩 보상 시스템 

### ISSUE THREAD

**Issue by zingzing2323** [CienProject2014/OneLevelHero_ProposalTeam#19]
대략적으로 정리한 내용 읽으시구  아이디어 생각나면 한 코멘트씩해주세요 ㅋㅋㅋ!!
사실 제가 맡은 부분이지만 어떤 엔딩보상을 하든 장점과 단점이 다 있는듯 해서..ㅠㅠ
좋은 생각있으면 남겨주세요~~

0. 엔딩보상 은  BONUS POINT의 용도와 유사 
1. 엔딩에 따른 보상 종류 정하기
   a.  아이템
   b. 스테이터스
   c. 스킬 
   d. 기타

2. 엔딩 보상 구체적으로 정하기
  a. 어떤 방식으로 ?
  b. 얼마나?
  c. 엔딩에 따라 차별적으로?
  d. 기타 등등

3. 엔딩 보상에 고려해야할 것들
   a. 성취감을 충분히 느끼게 하느냐
   b. 두번 이상 플레이시, 난이도, 흥미, 동기 를 해치지 않을 것
   c. 플레이 중 획득되는 것과 차별을 둘 것
   d. 설정 상 엔딩 보상은 "용사를 돕기위해 신이 주신 선물"

**Comment by dbstn003** [comment]
엔딩에 따른 보상은 스킬로 결정되었습니다.
