### ISSUE TITLE
'레벨' 표현

### ISSUE THREAD

**Issue by ramadrak** [CienProject2014/OneLevelHero_ProposalTeam#21]
스크립트에 '레벨'이란 표현이 나오는 것에 대해서 스토리팀의 의견이 많이 충돌을 했습니다.

레벨이란 표현이 스크립트에 나오면 어색하다는 의견이 있고, 이 게임 고유의 특이성을 살리는 표현이라는 의견도 있습니다.

다른 분들의 의견을 댓글로 올려주시면, 설정을 짜는데 도움이 될 듯 싶습니다.

**Comment by soyagok11** [comment]
레벨이라는건 캐릭터의 '레벨'과 던전의 '레벨'정도의 요소가 있는데

무슨 요소임?

**Comment by ramadrak** [comment]
여기선 캐릭터의 레벨인데요. 그 용사가 대화중에 "내 레벨이 떨어졌어" 라는 식의 말을 하는게 어색한지 아닌지에 대한 의견이 필요해서요.

**Comment by zingzing2323** [comment]
레벨 이라고 직접적인 표현보다는 다른 말로 표현할말은 없나용... 내레벨이 떨어졌어는 이상한거같은데 ㅜㅜ..!

**Comment by zingzing2323** [comment]
스크립트 읽는중인데 괜찮을거같기도하구..음 ..!

**Comment by lionstreet** [comment]
아무리 게임컨셉이 레벨다운일지라도 게임속의 캐릭터가 직접 레벨이라는 단어를 말하는 것은 확실히 어색하다. 특히 레벨은 게임의 시스템적 테마이기 때문에 이를 캐릭터가 직접 언급한다면 마치 캐릭터가 자신은 지금 게임속의 인물이라는 것을 인지하고 있는 듯한 느낌을 주게된다.

**Comment by HoraceVelmont** [comment]
그러네 힘이 약화되고 있다고 말하는게 나을듯
