### ISSUE TITLE
신이 시간을 돌린 이유

### ISSUE THREAD

**Issue by grandlord** [CienProject2014/OneLevelHero_ProposalTeam#3]
월요일 태영이형과 저, 벼리형과의 회의 결과 신이 시간을 돌린다는 것은 고정시키기로 했습니다.
문제점은 신이 시간을 돌린다면 왜 시간을 돌리는지에 대한 당위성에 문제가 생기는데요
이 부분에 대해 토의해 보았으면 좋겠습니다.

**Comment by koreakid91** [comment]
12/29 토의 때 나왔던 의견

마왕도 사실은 신이 만들었다.
신은 자신을 상징하는 용사라는 존재가 세상을 멸망시킬 마왕을 유일하게 무찌를 수 있는 구조를 통해 사람들의 신앙심을 얻으려는 목적을 가지고 있다.
따라서 용사 사망 혹은 마지막 날까지 용사가 마왕을 못 죽이거나 다른 곳에서 다른 일을 할 경우, 신이 시간을 돌린다는 설정.
이 경우 모든 멀티엔딩들은 어떠한 이유로도 결말에서 마왕을 안 죽이는 방향으로 가야 한다.
진엔딩 루트에서 용사와 마왕과 신에게 대항할만한 당위성도 생김.

**Comment by koreakid91** [comment]
이 내용을 채택하기로 합의되었으니 이슈 닫고 '신'에 대한 새 이슈 만들겠습니다.
